const app=document.querySelector('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const bySlug=s=>TUTORIALS.find(t=>t.slug===s);
const nav=()=>`<header class="topbar"><a class="brand" href="#/"><img src="assets/logo.png" alt="Central Boost"><span>Central<span>Boost</span></span></a><nav><a href="#/tutoriais">Tutoriais</a></nav></header>`;
const footer=()=>`<footer><div><strong>Central Boost</strong><p>Conhecimento técnico, explicado de forma prática.</p></div><div class="foot-links"><a href="#/tutoriais">Tutoriais</a><a href="#/sobre">Sobre</a><a href="#/contato">Contato</a></div><small>© ${new Date().getFullYear()} Central Boost</small></footer>`;
function card(t){return `<a class="card" href="#/tutorial/${t.slug}"><div class="card-icon"><img src="${t.icon}" alt=""></div><div class="card-body"><div class="eyebrow">${esc(t.category)} · ${esc(t.difficulty)}</div><h3>${esc(t.title)}</h3><p>${esc(t.short)}</p><div class="tags">${t.tags.slice(0,3).map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><span class="arrow">↗</span></a>`}
function video(id){return `<div class="video-shell" data-video="${esc(id)}"><div class="video-placeholder"><div class="play">▶</div><strong>Vídeo do tutorial</strong><span>O player é carregado somente quando você solicitar.</span><button type="button" onclick="loadVideo(this)">Carregar vídeo</button></div></div>`}
window.loadVideo=btn=>{const box=btn.closest('.video-shell'),id=box.dataset.video;box.innerHTML=`<iframe loading="lazy" src="https://www.youtube.com/embed/${encodeURIComponent(id)}?rel=0" title="Vídeo do Central Boost" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`};
function home(){return `${nav()}<main class="home-main"><section class="hero hero-simple"><div class="hero-copy"><div class="pill"><i></i> Tutoriais para Windows</div><h1>Windows.<br><em>Sem complicação.</em></h1><p>Guias em vídeo para otimização, desempenho e configurações do seu PC.</p><div class="hero-actions"><a class="btn primary" href="#/tutoriais">Ver tutoriais <b>→</b></a></div><div class="hero-topics"><span>Otimização</span><span>Desempenho</span><span>Configurações</span></div></div><div class="hero-art"><div class="orb"></div><img src="assets/Foguete2.png" alt="Foguete do Central Boost"></div></section></main>`}
function tutorials(){const q=new URLSearchParams(location.hash.split('?')[1]||'');return `${nav()}<main class="page"><section class="page-hero"><span class="kicker">BIBLIOTECA</span><h1>Tutoriais</h1><p>Encontre um guia, filtre por categoria ou pesquise pelo que você precisa.</p></section><section class="library"><div class="filters"><label class="search"><span>⌕</span><input id="search" placeholder="Buscar tutorial..." value="${esc(q.get('q')||'')}"></label><select id="cat"><option value="">Todas as categorias</option>${CATEGORIES.map(c=>`<option ${q.get('cat')===c.name?'selected':''}>${c.name}</option>`).join('')}</select><select id="sort"><option value="recent">Mais recentes</option><option value="alpha">A–Z</option></select></div><div id="results" class="cards">${TUTORIALS.map(card).join('')}</div></section></main>${footer()}`}
function tutorial(t){return `${nav()}<main class="article-page"><div class="breadcrumbs"><a href="#/tutoriais">Tutoriais</a><span>/</span><span>${esc(t.category)}</span><span>/</span><b>${esc(t.title)}</b></div><article><header class="article-head"><div><div class="eyebrow">${esc(t.category)}</div><h1>${esc(t.title)}</h1></div></header>${video(t.videoId)}</article></main>`}
function about(){return `${nav()}<main class="page narrow"><section class="page-hero"><span class="kicker">CENTRAL BOOST</span><h1>Tutoriais para Windows.</h1><p>Conteúdo em vídeo para otimização, desempenho e configurações do PC.</p></section></main>${footer()}`}
function contact(){return `${nav()}<main class="page narrow"><section class="page-hero"><span class="kicker">CONTATO</span><h1>Fale comigo.</h1><p>Use este espaço para enviar uma mensagem sobre o projeto.</p></section><form class="contact" action="https://formsubmit.co/adilson.junior942@gmail.com" method="post"><label>Nome<input name="nome" required></label><label>E-mail<input type="email" name="_replyto" required></label><label>Mensagem<textarea name="mensagem" rows="7" required></textarea></label><button class="btn primary" type="submit">Enviar mensagem →</button></form></main>${footer()}`}
function render(){const path=location.hash.slice(1)||'/';let html=path==='/'?home():path==='/tutoriais'?tutorials():path==='/sobre'?about():path==='/contato'?contact():path.startsWith('/tutorial/')?(bySlug(path.split('/')[2])?tutorial(bySlug(path.split('/')[2])):home()):home();app.innerHTML=html;if(path==='/tutoriais')setupFilters();document.title=path.startsWith('/tutorial/')?`${bySlug(path.split('/')[2])?.title||'Tutorial'} — Central Boost`:'Central Boost — Tecnologia sem complicação';window.scrollTo(0,0)}
function setupFilters(){const input=document.querySelector('#search'),cat=document.querySelector('#cat'),sort=document.querySelector('#sort'),out=document.querySelector('#results');const run=()=>{let a=TUTORIALS.filter(t=>(!cat.value||t.category===cat.value)&&(!input.value||`${t.title} ${t.short} ${t.tags.join(' ')}`.toLowerCase().includes(input.value.toLowerCase())));if(sort.value==='alpha')a.sort((x,y)=>x.title.localeCompare(y.title));else a.sort((x,y)=>y.date.localeCompare(x.date));out.innerHTML=a.length?a.map(card).join(''):`<div class="empty"><b>Nenhum tutorial encontrado.</b><span>Tente outra busca ou categoria.</span></div>`};input.oninput=run;cat.onchange=run;sort.onchange=run;run()}
window.addEventListener('hashchange',render);render();
